// <auto-generated />
using System;
using FileUploadIntegrationPrj.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileUploadIntegrationPrj.Migrations
{
    [DbContext(typeof(BookSearchDbContext))]
    partial class BookSearchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FileUploadIntegrationPrj.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<string>("BookAuthor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookGenre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookLocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookLocationPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DatePublished")
                        .HasColumnType("datetime2");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            BookAuthor = "Ray Dalio",
                            BookGenre = "Business & Money",
                            BookLocationName = "Principles_for_Dealing_World_Order_Ray_Dalio.jpg",
                            BookLocationPath = "",
                            BookTitle = "Principles for Dealing with the Changing World Order",
                            DatePublished = new DateTime(2021, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 2,
                            BookAuthor = "Rabbi Daniel Lapin",
                            BookGenre = "Self-help",
                            BookLocationName = "Business_Secrets_from_the_Bible_Rabbi_Daniel_Lapin.jpg",
                            BookLocationPath = "",
                            BookTitle = "Business Secrets from the Bible",
                            DatePublished = new DateTime(2014, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 3,
                            BookAuthor = "Bill Gates",
                            BookGenre = "History",
                            BookLocationName = "How_to_Avoid_a_Climate_Disaster_Bill_Gates.jpg",
                            BookLocationPath = "",
                            BookTitle = "How to Avoid a Climate Disaster",
                            DatePublished = new DateTime(2021, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 4,
                            BookAuthor = "Simon Sinek",
                            BookGenre = "Business & Money",
                            BookLocationName = "Start_with_Why_Simon_Sinek.jpg",
                            BookLocationPath = "",
                            BookTitle = "Start with Why",
                            DatePublished = new DateTime(2009, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 5,
                            BookAuthor = "Adam Grant",
                            BookGenre = "Business & Money",
                            BookLocationName = "Think_Again_Adam_Grant.jpg",
                            BookLocationPath = "",
                            BookTitle = "Think Again",
                            DatePublished = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 6,
                            BookAuthor = "James Clear",
                            BookGenre = "Health, Fitness & Dieting",
                            BookLocationName = "Atomic_Habits_James_Clear.jpg",
                            BookLocationPath = "",
                            BookTitle = "Atomic Habits",
                            DatePublished = new DateTime(2018, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 7,
                            BookAuthor = "Barack Obama",
                            BookGenre = "Biographies & Memoirs",
                            BookLocationName = "A_Promised_Land_Barack_Obama.jpg",
                            BookLocationPath = "",
                            BookTitle = "A Promised Land",
                            DatePublished = new DateTime(2020, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 8,
                            BookAuthor = "Dan Heath",
                            BookGenre = "Business & Money",
                            BookLocationName = "Upstream_Dan_Heath.jpg",
                            BookLocationPath = "",
                            BookTitle = "Upstream",
                            DatePublished = new DateTime(2020, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 9,
                            BookAuthor = "Gene Kim",
                            BookGenre = "Business & Money",
                            BookLocationName = "The_Phoenix_Project_Gene_Kim.jpg",
                            BookLocationPath = "",
                            BookTitle = "The Phoenix Project",
                            DatePublished = new DateTime(2013, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 10,
                            BookAuthor = "Satya Nadella",
                            BookGenre = "Biographies & Memoirs",
                            BookLocationName = "Hit_Refresh_Satya_Nadella.jpg",
                            BookLocationPath = "",
                            BookTitle = "Hit Refresh",
                            DatePublished = new DateTime(2017, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 11,
                            BookAuthor = "Jeffrey Gitomer",
                            BookGenre = "Business & Money",
                            BookLocationName = "The_Little_Red_Book_of_Selling_Jeffrey_Gitomer.jpg",
                            BookLocationPath = "",
                            BookTitle = "The Little Red Book of Selling",
                            DatePublished = new DateTime(2004, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 12,
                            BookAuthor = "Ray Dalio",
                            BookGenre = "Business & Money",
                            BookLocationName = "Principles_Life_and_Work_Ray_Dalio.jpg",
                            BookLocationPath = "",
                            BookTitle = "Principles: Life and Work",
                            DatePublished = new DateTime(2017, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 13,
                            BookAuthor = "Stephen_Meyer",
                            BookGenre = "Christian Books & Bibles",
                            BookLocationName = "Signature_in_the_Cell_Stephen_Meyer.jpg",
                            BookLocationPath = "",
                            BookTitle = "Signature in the Cell",
                            DatePublished = new DateTime(2009, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 14,
                            BookAuthor = "Kevin Horsley",
                            BookGenre = "Business & Money",
                            BookLocationName = "Unlimited_Memory_Kevin_Horsley.jpg",
                            BookLocationPath = "",
                            BookTitle = "Unlimited Memory",
                            DatePublished = new DateTime(2021, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 15,
                            BookAuthor = "Malcolm Gladwell",
                            BookGenre = "Business & Money",
                            BookLocationName = "Outliers_The_Story_of_Success_Malcolm_Gladwell.jpg",
                            BookLocationPath = "",
                            BookTitle = "Outliers",
                            DatePublished = new DateTime(2008, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 16,
                            BookAuthor = "Malcolm Gladwell",
                            BookGenre = "Business & Money",
                            BookLocationName = "David_and_Goliath_Malcolm_Gladwell.jpg",
                            BookLocationPath = "",
                            BookTitle = "David and Goliath",
                            DatePublished = new DateTime(2013, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 17,
                            BookAuthor = "Carol S. Dweck",
                            BookGenre = "Health, Fitness & Dieting",
                            BookLocationName = "Mindset_The_New_Psychology_of_Success_Carol_S._Dweck.jpg",
                            BookLocationPath = "",
                            BookTitle = "Mindset",
                            DatePublished = new DateTime(2006, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 18,
                            BookAuthor = "David Eagleman",
                            BookGenre = "Health, Fitness & Dieting",
                            BookLocationName = "Incognito_The_Secret_Lives_of_the_Brain_David_Eagleman.jpg",
                            BookLocationPath = "",
                            BookTitle = "Incognito",
                            DatePublished = new DateTime(2017, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 19,
                            BookAuthor = "Tony Robbins",
                            BookGenre = "Business & Money",
                            BookLocationName = "Unshakeable_Your_Financial_Freedom_Tony_Robbins.jpg",
                            BookLocationPath = "",
                            BookTitle = "Unshakeable",
                            DatePublished = new DateTime(2017, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 20,
                            BookAuthor = "Tony Robbins",
                            BookGenre = "Health, Fitness & Dieting",
                            BookLocationName = "Life_Force_Tony_Robbins.jpg",
                            BookLocationPath = "",
                            BookTitle = "Life Force",
                            DatePublished = new DateTime(2022, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
